policies:
  - type: commit
    spec:
      header:
        length: 80
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      gpg:
        required: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - "build"    # Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
          - "ci"       # Changes to our CI configuration files and scripts (examples: CircleCi, SauceLabs)
          - "docs"     # Documentation only changes
          - "feat"     # A new feature
          - "fix"      # A bug fix
          - "perf"     # A code change that improves performance
          - "refactor" # A code change that neither fixes a bug nor adds a feature
          - "test"     # Adding missing tests or correcting existing tests
        scopes: []
        descriptionLength: 72
